title: "Maths & Stats"
description: "Mathematics and Statistics reference"

color_scheme: "dark"
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - CREDITS
  - CNAME
  - README.md
  - Dockerfile

